[color]
waiting = 0x00A9FF
incorrect = 0xFF7676
correct = 0x40A578
quiz_complete = 0xE7D27C

[quiz]
lenght = 10

[strings]
quiz_complete_embed_title = ":trophy: Quiz completed!"
question_already_answered_error = "This question has already been answered."
explanation_label = "Explanation"

[[questions.math]]
question = "Aprēķini izteiksmes 5m – 4 vērtību, ja m = 3"
answer = "11"
incorrect_options = ["4", "1", "-2"]
explanation = "Ievieto mainīgā vietā tā vērtību un izpildi darbības. 5 ∙ 3 − 4 = 11"

[[questions.math]]
question = "Izpildi darbības. 5b – 3 – 2b ="
answer = "3b − 3"
incorrect_options = ["3b − 2", "3b + 2", "b − 3"]
explanation = "Saīsina 5b - 2b = 3b, skaitļu daļa paliek neskarta."

[[questions.math]]
question = "Izpildi darbības. (2a + 3)(2a – 6) – 3(a – 1) ="
answer = "4a^2 − 9a − 15"
incorrect_options = ["4a^2 + 9a − 15", "4a^2 − 3a − 15", "4a^2 − 9a + 15"]
explanation = "Jāizvērš un jāvienkāršo."

[[questions.math]]
question = "Monomu 6x^8 dalot ar monomu 3x^2, iegūst"
answer = "2x^6"
incorrect_options = ["3x^4", "2x^4", "3x^6"]
explanation = "Jāizmanto distributīvo īpašību, lai izplatītu un pēc tam saliktu līdzīgus izteikumus, kā arī jāievēro zīmju pareizība,"

[[questions.math]]
question = "Izteiksmes 6^–2 vērtība ir"
answer = "1/36"
incorrect_options = ["36", "-36", "-1/36"]
explanation = "6 ir jākāpina ar -2."

[[questions.math]]
question = "Aprēķini. 1,2023 ∙ 10^4 ="
answer = "12023"
incorrect_options = ["120,23", "120230", "1202,3"]
explanation = "1,2023 * 10^4 = 1,2023 * 10000 = 12023"

[[questions.math]]
question = "Aprēķini izteiksmes vērtību. √64 ="
answer = "8"
incorrect_options = ["16", "1", "128"]
explanation = "8^2 = 64"

[[questions.math]]
question = "Aprēķini izteiksmes vērtību. (3√2)^2"
answer = "18"
incorrect_options = ["6", "9", "12"]
explanation = "Izvelkot no iekavām, iegūst 3^2 * √2^2, 3^2 = 9 un √2^2 = 2. 9 * 2 = 18"

[[questions.math]]
question = "Kurš skaitlis uz skaitļu ass ir vistuvākais skaitlim √14?"
answer = "3,75"
incorrect_options = ["3,25", "4,25", "7"]
explanation = "√14 = ~3.742"

[[questions.math]]
question = "Sadali reizinātājos. 2a + 8 ="
answer = "2(a + 4)"
incorrect_options = ["10a", "2 * a + 8", "2(a + 8)"]
explanation = "2a un 8 var dalīt ar 2 un izlikt pirms iekavām."

[[questions.math]]
question = "Sadali reizinātājos. a^2 – 64 ="
answer = "(a − 8)(a + 8)"
incorrect_options = ["2(a - 32)", "2(a - 8)", "(a - 8)^2"]
explanation = "Kvadrātu starpība"

[[questions.math]]
question = "Kāda ir atbilde uz galīgo jautājumu par dzīvi, Visumu un visu?"
answer = 42
incorrect_options = [13, "Zinātne", "Mīlestība"]
explanation = "The Hitchhiker's Guide to the Galaxy"

[[questions.math]]
question = "Sadali reizinātājos. 1 – 6a + 9a^2 ="
answer = "(1 − 3a)^2"
incorrect_options = ["(1 + 3a)^2", "(1 − 3a)(1 + 3a)", "(1 − 9a)(1 + a)"]
explanation = "Izmanto kvadrāta formulas atpazīšanu."

[[questions.math]]
question = "Cilindra pamata rādiuss ir 8 cm, bet cilindra augstums ir 0,5 cm. Kāds ir cilindra tilpums?"
answer = "32π cm^3"
incorrect_options = ["64π cm^3", "128π cm^3", "320π cm^3"]
explanation = "Izmanto formulu V = πr²h, kur r ir pamata rādiuss un h ir augstums."

[[questions.math]]
question = "Pārveidojot a^3 b^3, iegūst"
answer = "(ab)^3"
incorrect_options = ["(ab)^6", "ab^6", "ab^3"]
explanation = "Reizinot divus skaitļus ar vienādām pakāpēm, var izveidot kopēju bāzi ar kopējo pakāpi."

[[questions.math]]
question = "Darba alga x (EUR) tika palielināta par 30%. Kura izteiksme izsaka darba algu pēc palielināšanas?"
answer = "x + 0,3x"
incorrect_options = ["x + 30", "0,3x", "x + x + 30"]
explanation = "Palielinot algu par 30%, jaunā alga ir sākotnējā alga plus 30% no sākotnējās algas."

[[questions.math]]
question = "Aprēķini. 43,2 - 1,12"
answer = "42,08"
incorrect_options = ["42,1", "42,22", "544"]
explanation = "Atņemot vienu skaitli no otra, otrais paliek mazāks par pirmo skaitli."

[[questions.math]]
question = "Aprēķini. 1,2 * 0,15"
answer = "0,18"
incorrect_options = ["0,12", "0,20", "1,35"]
explanation = "Reizinot 1,2 ar 0,15 iegūst 0,18."

[[questions.math]]
question = "Aprēķini. 5,1 : 5"
answer = "1 + 1/50"
incorrect_options = ["1,05", "1 + 2/50", "1,02"]
explanation = "Pārveidojot uz parasto daļu, 51/10 : 5 = 51 / 10 * 5 = 51 / 50 = 1 + 1/50"

[[questions.math]]
question = "Aprēķini. 2 : 1/3"
answer = "6"
incorrect_options = ["2/3", "6/3", "4"]
explanation = "Dalot ar 1/3 ir tas pats, kas reizinot ar 3. 2 * 3 = 6"

[[questions.math]]
question = "Aprēķini. (1 + 1/6) - 2/9"
answer = "17/18"
incorrect_options = ["5/6", "1", "7/9"]
explanation = "Jānovienādo saucēji un jāatņem."

[[questions.math]]
question = "Aprēķini. (1 + 2/3) * 0,16 + 1/3 * 0,16"
answer = "32"
incorrect_options = ["0.16", "16", "0.64"]
explanation = "Jāizpilda darbības pareizā secībā."

[[questions.english]]
question = "Which of the given key words can be used in Present Continuous?"
answer = "Listen!"
incorrect_options = ["ever", "in spring", "in 2015"]
explanation = "It is a key word of Present Continuous"

[[questions.english]]
question = "Which of the given key words can be used in Present Continuous?"
answer = "tomorrow"
incorrect_options = ["when I was a child", "at 6 o'clock", "so far"]
explanation = "This key word can be used in Present Continuous when we want to speak about fixed arrangements in the near future."

[[questions.english]]
question = "Complete the sentences with the correct Present Continuous affirmative form: Jenny ___ online right now."
answer = "is chatting"
incorrect_options = ["are chatting", "do chating", "is chating"]
explanation = "Formula of Present Continuous/ Affirmative: Subject + am/ is/ are + Ving"

[[questions.english]]
question = "Complete the sentences with the correct Present Continuous negative form: We ____ to Amy now."
answer = "are not speaking"
incorrect_options = ["are not speak", "are speaking not", "do speaking not"]
explanation = "Formula of Present Continuous/ Negative: Subject + am/ is/ are + NOT + Ving"

[[questions.english]]
question = "Complete the sentences with the correct Present Continuous interrogative form: ____ how to use a computer this week?"
answer = "Is your granny learning"
incorrect_options = [
    "Are your granny learn",
    "Is your grannies learnning",
    "Do your granny learnning",
]
explanation = "Formula of Present Continuous/ Interrogative: (Question Word) + subject + am/ is/ are + Ving … ?"

[[questions.english]]
question = "Choose Present Perfect where possible: My dad ____ clothes in a second-hand shop."
answer = "has never bought"
incorrect_options = ["hasn't never bought", "never bought", "do not bought"]
explanation = "The key word is \"never\". And it is not said 'when'. So we use Present Perfect."

[[questions.english]]
question = "Choose Present Perfect where possible: ____ in a designer shop last Thursday?"
answer = "Were you"
incorrect_options = ["Did you be", "Have you been", "Did you been"]
explanation = "The key word is \"last Sunday\". And it is said 'when'. So we use Past Simple."

[[questions.english]]
question = "Complete the sentence with an interrogative pronoun: ____ pronouns do you use?"
answer = "What"
incorrect_options = ["Which", "Where", "Whose"]
explanation = "WHAT can be used to ask about objects or people. For example: What time is it? What is your name?"

[[questions.english]]
question = "Which of the given key words are usually used in Past Simple?"
answer = "two weeks ago"
incorrect_options = ["up to now", "usually", "soon"]
explanation = "It is a key word of Past Simple. The other key words: usually — Present Simple; soon — Future Simple (will); up to now — Present Perfect"

[[questions.english]]
question = "Which of the given key words are usually used in Past Simple?"
answer = "last month"
incorrect_options = ["at present", "lately", "in summers"]
explanation = "It is a key word of Past Simple. The other key words: usually — Present Simple; soon — Future Simple (will); up to now — Present Perfect"
