[color]
waiting = 0x00A9FF
incorrect = 0xFF7676
correct = 0x40A578

[[question]]
question = "Aprēķini izteiksmes 5m – 4 vērtību, ja m = 3"
answer = 11
incorrect_options = []
explanation = "5 ∙ 3 − 4 = 11"

[[question]]
question = "Izpildi darbības. 5b – 3 – 2b ="
answer = "3b − 3"
incorrect_options = ["3b − 2", "3b + 2", "b − 3"]
explanation = "Saīsina 5b - 2b = 3b, skaitļu daļa paliek neskarta."

[[question]]
question = "Izpildi darbības. (2a + 3)(2a – 6) – 3(a – 1) ="
answer = "4a^2 − 9a − 15"
incorrect_options = ["4a^2 + 9a − 15", "4a^2 − 3a − 15", "4a^2 − 9a + 15"]
explanation = "Jāizvērš un jāvienkāršo."

[[question]]
question = "Monomu 6x^8 dalot ar monomu 3x^2, iegūst"
answer = "2x^6"
incorrect_options = ["3x^4", "2x^4", "3x^6"]
explanation = "Jāizmanto distributīvo īpašību, lai izplatītu un pēc tam saliktu līdzīgus izteikumus, kā arī jāievēro zīmju pareizība,"

[[question]]
question = "Izteiksmes 6^–2 vērtība ir"
answer = "1/36"
incorrect_options = ["36", "-36", "-1/36"]
explanation = "6 ir jākāpina ar -2."

[[question]]
question = "Aprēķini. 1,2023 ∙ 10^4 ="
answer = "12023"
incorrect_options = ["120,23", "120230", "1202,3"]
explanation = "1,2023 * 10^4 = 1,2023 * 10000 = 12023"

[[question]]
question = "Aprēķini izteiksmes vērtību. √64 ="
answer = "8"
incorrect_options = ["16", "1", "128"]
explanation = "8^2 = 64"

[[question]]
question = "Aprēķini izteiksmes vērtību. (3√2)^2"
answer = "18"
incorrect_options = ["6", "9", "12"]
explanation = "Izvelkot no iekavām, iegūst 3^2 * √2^2, 3^2 = 9 un √2^2 = 2. 9 * 2 = 18"

[[question]]
question = "Kurš skaitlis uz skaitļu ass ir vistuvākais skaitlim √14?"
answer = "3,75"
incorrect_options = ["3,25", "4,25", "7"]
explanation = "√14 = ~3.742"

[[question]]
question = "Sadali reizinātājos. 2a + 8 ="
answer = "2(a + 4)"
incorrect_options = ["10a", "2 * a + 8", "2(a + 8)"]
explanation = "2a un 8 var dalīt ar 2 un izlikt pirms iekavām."

[[question]]
question = "Sadali reizinātājos. a^2 – 64 ="
answer = "(a − 8)(a + 8)"
incorrect_options = ["2(a - 32)", "2(a - 8)", "(a - 8)^2"]
explanation = "Kvadrātu starpība"

[[question]]
question = "Kāda ir atbilde uz galīgo jautājumu par dzīvi, Visumu un visu?"
answer = 42
incorrect_options = [13, "Zinātne", "Mīlestība"]
explanation = "The Hitchhiker's Guide to the Galaxy"

[[question]]
question = "Sadali reizinātājos. 1 – 6a + 9a^2 ="
answer = "(1 − 3a)^2"
incorrect_options = ["(1 + 3a)^2", "(1 − 3a)(1 + 3a)", "(1 − 9a)(1 + a)"]
explanation = "Izmanto kvadrāta formulas atpazīšanu."

[[question]]
question = "Cilindra pamata rādiuss ir 8 cm, bet cilindra augstums ir 0,5 cm. Kāds ir cilindra tilpums?"
answer = "32π cm^3"
incorrect_options = ["64π cm^3", "128π cm^3", "320π cm^3"]
explanation = "Izmanto formulu V = πr²h, kur r ir pamata rādiuss un h ir augstums."

[[question]]
question = "Pārveidojot a^3 b^3, iegūst"
answer = "(ab)^3"
incorrect_options = ["(ab)^6", "ab^6", "ab^3"]
explanation = "Reizinot divus skaitļus ar vienādām pakāpēm, var izveidot kopēju bāzi ar kopējo pakāpi."

[[question]]
question = "Darba alga x (EUR) tika palielināta par 30%. Kura izteiksme izsaka darba algu pēc palielināšanas?"
answer = "x + 0,3x"
incorrect_options = ["x + 30", "0,3x", "x + x + 30"]
explanation = "Palielinot algu par 30%, jaunā alga ir sākotnējā alga plus 30% no sākotnējās algas."

[[question]]
question = "Aprēķini. 43,2 - 1,12"
answer = "42,08"
incorrect_options = ["42,1", "42,2", "544"]
explanation = "Atņemot vienu skaitli no otra, otrais paliek mazāks par pirmo skaitli."

[[question]]
question = "Aprēķini. 1,2 * 0,15"
answer = "0,18"
incorrect_options = ["0,12", "0,20", "1,35"]
explanation = "Reizinot 1,2 ar 0,15 iegūst 0,18."

[[question]]
question = "Aprēķini. 5,1 : 5"
answer = "1 + 1/50"
incorrect_options = ["1.04", "1 + 2/50", "1.05"]
explanation = "Pārveidojot uz parasto daļu, 51/10 : 5 = 51 / 10 * 5 = 51 / 50 = 1 + 1/50"

[[question]]
question = "Aprēķini. 2 : 1/3"
answer = "6"
incorrect_options = ["2/3", "6/3", "4"]
explanation = "Dalot ar 1/3 ir tas pats, kas reizinot ar 3. 2 * 3 = 6"

[[question]]
question = "Aprēķini. (1 + 1/6) - 2/9"
answer = "17/18"
incorrect_options = ["5/6", "1", "7/9"]
explanation = "Jānovienādo saucēji un jāatņem."

[[question]]
question = "Aprēķini. (1 + 2/3) * 0,16 + 1/3 * 0,16"
answer = "32"
incorrect_options = ["0.16", "16", "0.64"]
explanation = "Jāizpilda darbības pareizā secībā."
